name: clang-tidy
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-clang@v1
        with:
          version: 15
      - run: sudo apt-get -y install bear
      - run: bear -- make all test
      - run: sudo apt-get -y install clang-tidy
      - run: clang-tidy src/**/*.{c,h} test/**/*.c
