name: clang-tidy
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15"
      - run: sudo apt install bear
      - run: bear -- make all test
      - run: clang-tidy src/**/*.{c,h} test/**/*.c
