name: clang-tidy
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: smay1613/clang-tidy-action@master
